# Generated by Django 2.1 on 2018-08-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_auto_20180819_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='required',
            field=models.TextField(blank=True),
        ),
    ]
